### ISSUE TITLE
Firebase development

### ISSUE THREAD

**Issue by kbonillas** [ElizabethCAllen/YALT#15]
- [ ] share firebase with team members

- [ ] install node.js on systems

- [ ] install firebase tools

- [ ] merge the firebase tools branch into develop

- [ ] figure out the proper section of development for firebase project (authentication)

- [ ] database for storing user info

- [ ] research hosting on/pushing to firebase

**Comment by ElizabethCAllen** [comment]
Ran out of time for Firebase
